# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('peer', '0003_auto_20160624_1316'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ivr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('greeting', models.FileField(upload_to='ivr')),
                ('waiting', models.DurationField()),
                ('attempts', models.PositiveIntegerField()),
                ('key0_object_id', models.PositiveIntegerField()),
                ('key1_object_id', models.PositiveIntegerField()),
                ('key2_object_id', models.PositiveIntegerField()),
                ('key3_object_id', models.PositiveIntegerField()),
                ('key4_object_id', models.PositiveIntegerField()),
                ('key5_object_id', models.PositiveIntegerField()),
                ('key6_object_id', models.PositiveIntegerField()),
                ('key7_object_id', models.PositiveIntegerField()),
                ('key8_object_id', models.PositiveIntegerField()),
                ('key9_object_id', models.PositiveIntegerField()),
                ('end_object_id', models.PositiveIntegerField()),
                ('end_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_content_type', to='contenttypes.ContentType')),
                ('key0_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key0_content_type', to='contenttypes.ContentType')),
                ('key1_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key1_content_type', to='contenttypes.ContentType')),
                ('key2_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key2_content_type', to='contenttypes.ContentType')),
                ('key3_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key3_content_type', to='contenttypes.ContentType')),
                ('key4_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key4_content_type', to='contenttypes.ContentType')),
                ('key5_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key5_content_type', to='contenttypes.ContentType')),
                ('key6_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key6_content_type', to='contenttypes.ContentType')),
                ('key7_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key7_content_type', to='contenttypes.ContentType')),
                ('key8_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key8_content_type', to='contenttypes.ContentType')),
                ('key9_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key9_content_type', to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('all', 'Call to all subscribers'), ('random', 'Random')], max_length=32)),
                ('moh', models.FileField(upload_to='moh')),
                ('waiting', models.DurationField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('subscribers', models.ManyToManyField(to='peer.Subscriber')),
            ],
        ),
    ]
